name: Feature Request
description: Propose a new capability or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Suggested behavior/API/CLI flow.
    validations:
      required: true
  - type: textarea
    id: security
    attributes:
      label: Security Considerations
      description: How does this impact policy, approvals, or audit?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
